import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  if (req.method !== 'POST') {
    return new Response('Method not allowed', { status: 405, headers: corsHeaders });
  }

  try {
    console.log('Starting ideogram generation request...');
    
    // Create service role client for database/storage operations
    const serviceRoleClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    // Try to get user from auth (if JWT provided)
    let userId = null;
    let guestId = null;
    
    const authHeader = req.headers.get('Authorization');
    if (authHeader) {
      const userClient = createClient(
        Deno.env.get('SUPABASE_URL') ?? '',
        Deno.env.get('SUPABASE_ANON_KEY') ?? '',
        {
          global: {
            headers: { Authorization: authHeader },
          },
        }
      );
      
      const { data: { user }, error: userError } = await userClient.auth.getUser();
      if (!userError && user) {
        userId = user.id;
        console.log('Authenticated user:', userId);
      }
    }
    
    // If no authenticated user, generate a guest ID
    if (!userId) {
      guestId = `guest_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
      console.log('Using guest ID:', guestId);
    }

    const body = await req.json();
    console.log('Request body:', body);

    const { prompt, aspect_ratio, style_type, model, negative_prompt } = body;

    if (!prompt) {
      return new Response('Missing prompt', { status: 400, headers: corsHeaders });
    }

    // Insert job record
    const { data: job, error: jobError } = await serviceRoleClient
      .from('gen_jobs')
      .insert({
        user_id: userId || guestId,
        prompt,
        negative_prompt: negative_prompt || '',
        style: style_type || 'DESIGN',
        aspect: aspect_ratio || 'ASPECT_1_1',
        status: 'running'
      })
      .select()
      .single();

    if (jobError) {
      console.error('Job creation error:', jobError);
      return new Response('Failed to create job', { status: 400, headers: corsHeaders });
    }

    console.log('Created job:', job.id);

    try {
      // Call Ideogram API
      const ideogramApiKey = Deno.env.get('IDEOGRAM_API_KEY');
      if (!ideogramApiKey) {
        throw new Error('Ideogram API key not configured');
      }

      console.log('Calling Ideogram API...');
      const ideogramResponse = await fetch('https://api.ideogram.ai/generate', {
        method: 'POST',
        headers: {
          'Api-Key': ideogramApiKey,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          image_request: {
            prompt,
            aspect_ratio,
            model,
            magic_prompt_option: "AUTO",
            seed: Math.floor(Math.random() * 1000000),
            style_type,
            negative_prompt
          }
        }),
      });

      if (!ideogramResponse.ok) {
        const errorText = await ideogramResponse.text();
        console.error('Ideogram API error:', errorText);
        throw new Error(`Ideogram API error: ${ideogramResponse.status} - ${errorText}`);
      }

      const ideogramData = await ideogramResponse.json();
      console.log('Ideogram response:', ideogramData);

      if (!ideogramData.data || ideogramData.data.length === 0) {
        throw new Error('No images generated by Ideogram');
      }

      const imageUrl = ideogramData.data[0].url;
      
      // Download the image
      console.log('Downloading image from:', imageUrl);
      const imageResponse = await fetch(imageUrl);
      if (!imageResponse.ok) {
        throw new Error(`Failed to download image: ${imageResponse.status}`);
      }

      const imageBlob = await imageResponse.blob();
      const imageBuffer = await imageBlob.arrayBuffer();
      const imageBytes = new Uint8Array(imageBuffer);

      // Upload to Supabase Storage
      const storagePath = `${userId || guestId}/${job.id}.png`;
      console.log('Uploading to storage path:', storagePath);
      
      const { error: uploadError } = await serviceRoleClient.storage
        .from('gen-images')
        .upload(storagePath, imageBytes, {
          contentType: 'image/png',
          upsert: true
        });

      if (uploadError) {
        console.error('Upload error:', uploadError);
        throw new Error(`Storage upload failed: ${uploadError.message}`);
      }

      // Create signed URL
      const { data: signedUrlData, error: signedUrlError } = await serviceRoleClient.storage
        .from('gen-images')
        .createSignedUrl(storagePath, 3600); // 1 hour expiry

      if (signedUrlError) {
        console.error('Signed URL error:', signedUrlError);
        throw new Error(`Failed to create signed URL: ${signedUrlError.message}`);
      }

      // Update job with success
      const { error: updateError } = await serviceRoleClient
        .from('gen_jobs')
        .update({
          status: 'done',
          image_url: signedUrlData.signedUrl
        })
        .eq('id', job.id);

      if (updateError) {
        console.error('Job update error:', updateError);
      }

      console.log('Generation successful, returning signed URL');
      return new Response(JSON.stringify({
        job_id: job.id,
        image_url: signedUrlData.signedUrl
      }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });

    } catch (error) {
      console.error('Generation error:', error);
      
      // Update job with error
      await serviceRoleClient
        .from('gen_jobs')
        .update({
          status: 'error',
          error: error.message
        })
        .eq('id', job.id);

      return new Response(JSON.stringify({
        job_id: job.id,
        error: error.message
      }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

  } catch (error) {
    console.error('Request processing error:', error);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});